services:
  - type: web
    name: f1-fantasy
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: node dist/index.cjs
    envVars:
      - key: NODE_ENV
        value: production
